version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: giphy-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      giphy-network:
        ipv4_address: 172.28.1.10
    ports:
      - "9003:9003"
    environment:
      PHP_IDE_CONFIG: "serverName=giphy-api"
      XDEBUG_CONFIG: "client_host=172.28.0.1"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: giphy-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      giphy-network:
        ipv4_address: 172.28.1.20
    command: --default-authentication-plugin=mysql_native_password

  nginx:
    image: nginx:alpine
    container_name: giphy-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      giphy-network:
        ipv4_address: 172.28.1.30
    depends_on:
      - app

networks:
  giphy-network:
    name: giphy-api-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1

volumes:
  mysql_data:
    name: giphy-api-mysql-data
    driver: local 