version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: giphy-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - giphy-network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: giphy-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - giphy-network
    command: --default-authentication-plugin=mysql_native_password

  nginx:
    image: nginx:alpine
    container_name: giphy-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - giphy-network
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: giphy-api-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - giphy-network

networks:
  giphy-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local 