@startuml
left to right direction
skinparam packageStyle rectangle

actor "Usuario" as user

rectangle "API Giphy" {
  usecase "Autenticarse (Login)" as UC1
  usecase "Buscar GIFs" as UC2
  usecase "Obtener GIF por ID" as UC3
  usecase "Guardar GIF favorito" as UC4
}

user --> UC1
user --> UC2
user --> UC3
user --> UC4

note right of UC1
  Permite la autenticación para 
  operar con la API.
  Devuelve un token con expiración 
  de 30 minutos.
end note

note right of UC2
  Buscar gifs por una frase o término.
  Parámetros:
  - QUERY (requerido)
  - LIMIT (opcional)
  - OFFSET (opcional)
end note

note right of UC3
  Obtener información de un 
  gift específico por ID
end note

note right of UC4
  Almacenar para un usuario 
  un gif favorito.
  Parámetros:
  - GIF_ID
  - ALIAS
  - USER_ID
end note

@enduml 